# -*- coding: utf-8 -*-
"""Prompt_Versioning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZXEzZTClet2KUgNNykbeZZKteJw2Z6s3

Name: Pranayan Pandey

Project: Prompt Versioning & A/B Testing Platform
Manage and track prompt experiments, auto-evaluate performance metrics, and roll out the best-performing prompts automatically.

# PromptDeck — Prompt Versioning & A/B Testing Platform

**The GitHub for Prompts.**  
Manage, version, A/B test, auto-evaluate, and deploy the highest-performing prompts across your LLM applications — automatically.


## Why PromptDeck Exists

Prompt engineering is the new bottleneck in production LLM applications. Most teams:

- Copy-paste prompts across codebases
- Have no versioning or history
- Manually test prompt changes
- Guess which prompt is "better"
- Can't reproduce results from last week
"""

pip install promptdeck

"""Initialize in app"""

from promptdeck import PromptDeckClient

pd = PromptDeckClient(api_key="pd_sk_...")

"""Version and test a prompt"""

@pd.prompt(
    name="customer-support-v2",
    tags=["support", "tone:friendly"],
    metadata={"author": "alice@company.com"}
)
def customer_support_prompt(user_query: str, context: str):
    return f"""
    You are a world-class customer support agent.
    Respond in a friendly and professional tone.

    User query: {user_query}
    Relevant context: {context}

    Response:
    """

"""Run A/B test automatically"""

# 70% traffic → current production prompt
# 30% traffic → customer-support-v2
pd.ab_test(
    experiment_name="support-tone-experiment",
    variants=["customer-support-v1", "customer-support-v2"],
    traffic_allocation=[0.7, 0.3]
)

"""Auto-evaluate with LLM judge"""

pd.auto_evaluate(
    experiment="support-tone-experiment",
    judge_prompt="judge/helpfulness-v3",
    metrics=["helpfulness", "conciseness", "brand_voice"],
    sample_size=500
)

"""Auto Pramotion Example"""

pd.auto_promote(
    experiment="support-tone-experiment",
    metric="helpfulness",
    min_improvement=0.05,  # 5% better
    auto_rollback_if_regression=True
)

